updating golang.org/x/net module
As far as I can tell, this is required to support freebsd/arm64.
Without this, building on that os/platform combo gives this error:

    undefined: uint128